const Product = {
    fields: {
        Product_Type: {type: 'select'},
        Name: {type: 'string'},
        Stock: {type: 'int'},
        Price: {type: 'int'},
        Discount: {type: 'int'},
        Final_Price: {type: 'int'},
        Image: {type: 'file'},
        Video: {type: 'file'},
        Certificate_Image: {type: 'file'},
        Shape: {type: 'select'},
        Carat: {type: 'string'},
        Cut: {type: 'select'},
        Polish: {type: 'select'},
        Symmetry: {type: 'select'},
        Girdle_Min: {type: 'select'},
        Girdle_Max: {type: 'select'},
        Girdle_Condition: {type: 'string'},
        Pavilion_Depth: {type: 'string'},
        Pavilion_Angle: {type: 'string'},
        Hearts_Arrows: {type: 'select'},
        Eye_Clean: {type: 'select'},
        Type: {type: 'string'},
        Depth_Percent: {type: 'string'},
        Table_Percent: {type: 'string'},
        Ratio: {type: 'string'},
        Meas_Length: {type: 'string'},
        Meas_Width: {type: 'string'},
        Meas_Depth: {type: 'string'},
        Pair: {type: 'select'},
        Culet_Carat: {type: 'select'},
        Culet_Condition: {type: 'string'},
        Crown_Height: {type: 'string'},
        Crown_Angle: {type: 'string'},
        BGM: {type: 'string'},
        Color: {type: 'select'},
        Fancy_Color_Dominant_Color: {type: 'select'},
        Fancy_Color_Overtone: {type: 'select'},
        Clarity: {type: 'select'},
        Fancy_Color_Secondary_Color: { type: 'string' },
        Fancy_Color_Intensity: {type: 'select'},
        Fluor_Color: {type: 'string'},
        Fluor_Intensity: {type: 'select'},
        Lab: {type: 'select'},
        Certification: {type: 'select'},
    },

    selectOptions: {
        Shape: ['Asscher', 'Baguette', 'Briolette', 'Bullet', 'Cushion', 'Cushion Modified Brilliant', 'Emerald', 'Eurocut', 'Flanders', 'Half Moon', 'Heart', 'Hexagonal', 'Kite', 'Lozenge', 'Marquise', 'Octagonal', 'Old Miner', 'Oval', 'Pear', 'Pentagonal', 'Princess', 'Radiant', 'Round', 'Rose Cut', 'Shield', 'Star', 'Square Emerald', 'Tapered Baguette', 'Tapered Bullet', 'Trapezoid', 'Triangle', 'Trilliant', 'Other', 'Square', 'Ideal Square', 'Ideal Oval', 'Ideal Cushion', 'Ideal Heart', 'Cushion Brilliant', 'Radiant-R', 'Radiant-S', 'Baguette A', 'HMoon B', 'HMoon Step', 'Old Fancy', 'Taper B', 'Taper A', 'Trapz B', 'Trapz S', 'Cadi Step', 'Carre Square Baguette', 'Trapezoid Brilliant', 'Trapezoid Step', 'Radiant Modified', 'Antique Cushion', 'Old European', 'Cushion Long', 'Cushion Square', 'Radiant Square', 'Ashoka', 'Criss-Cut', 'Butterfly', 'HorseHead', 'Ovalisa', 'Mix', 'Buddha'],
        Cut: ['Poor', 'Fair', 'Good', 'Very Good', 'Excellent', 'Ideal', '8X'],
        Polish: ['Poor', 'Fair', 'Good', 'Very Good', 'Excellent', 'Ideal'],
        Symmetry: ['Poor', 'Fair', 'Good', 'Very Good', 'Excellent', 'Ideal'],
        Girdle_Min: ['Extremely Thin', 'Very Thin', 'Slightly Thin', 'Thin', 'Medium', 'Thick', 'Slightly Thick', 'Very Thick', 'Extremely Thick'],
        Girdle_Max: ['Extremely Thin', 'Very Thin', 'Slightly Thin', 'Thin', 'Medium', 'Thick', 'Slightly Thick', 'Very Thick', 'Extremely Thick'],
        Hearts_Arrows: ['Yes', 'No'],
        Eye_Clean: ['Yes', 'No'],
        Culet_Carat: ['XL', 'VL', 'L', 'SL', 'M', 'S', 'VS', 'N'],
        Color: ['D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z'],
        Fancy_Color_Dominant_Color: ['Green', 'Brown-Pink', 'Green-Blue', 'Olive', 'Blue', 'Yellow', 'Pink-Brown', 'Purple', 'Violet', 'White', 'Red', 'Pink', 'Black', 'Gray', 'Brown', 'Orange', 'Chameleon', 'Other'],
        Fancy_Color_Overtone: ['Pinkish', 'Orangy', 'Brownish', 'Purplish', 'Blackish', 'Brownish-Orangy', 'Yellow', 'Yellowish', 'Pink', 'Blue', 'Bluish', 'Red', 'Reddish', 'Green', 'Greenish', 'Purple', 'Orange', 'Violet', 'Violetish', 'Gray', 'Grayish', 'Black', 'Brown', 'Champagne', 'Cognac', 'Chameleon', 'White', 'Brownish-Yellowish', 'Greenish-Yellow', 'Brownish-Purple', 'Brownish-Greenish', 'Grayish-Yellowish', 'Gray-Greenish', 'Grayish-Greenish', 'Brown-Greenish', 'Gray-Yellowish', 'Brownish-Yellow', 'Brownish-Purplish'],
        Clarity: ['FL', 'IF', 'VVS1', 'VVS2', 'VS1', 'VS2', 'SI1', 'SI2', 'SI3', 'I1', 'I2', 'I3', 'SI', 'VS', 'VS-SI', 'VVS', 'P1', 'P2', 'SI1-SI2', 'SI-P1', 'VVS2-VS1', 'FL-IF', 'IF-VVS1', 'VVS1-VVS2', 'VS1-VS2', 'VS2-SI1', 'I2-I3', 'SI2-SI3', 'SI3-I1', 'I1-I2', 'VVS-VS', 'SIAV'],
        Fancy_Color_Intensity: ['Faint', 'Very Light', 'Light', 'Fancy Light', 'Fancy', 'Fancy Intense', 'Fancy Vivid', 'Fancy Dark', 'Fancy Deep'],
        Fluor_Intensity: ['Very Strong', 'Strong', 'Medium', 'Faint', 'None', 'Very Slight', 'Slight'],
        Lab: ['IGI', 'GIA', 'GCAL', 'AGS', 'HRD', 'SGL', 'GSI', 'Other', 'None'],
        Certification: ['Sustainability Rated','Climate Neutral' , 'Sustainability Rated and Climate Neutral' , 'None'],
        Pair : ['Yes','No'],
        Product_Type: ['Diamond','Lab Grown']
    }
};

export default Product;
